USER=$(whoami)

cd ~/Workspaces/intrarobots_ws
catkin_make

cd ~/Workspaces/intrarobots_ws/src

catkin_create_pkg franka_description xacro

catkin_create_pkg robotic_arm_descriptions joint_state_publisher joint_state_publisher_gui robot_state_publisher roslaunch rviz xacro 

catkin_create_pkg robotic_arm_gazebo controller_manager effort_controllers gazebo_ros gazebo_ros_control joint_state_controller joint_trajectory_controller robotic_arm_descriptions franka_description 

catkin_create_pkg robotic_arm_moveit robotic_arm_gazebo joint_state_publisher moveit_fake_controller_manager moveit_kinematics moveit_planners_ompl moveit_ros_move_group moveit_ros_visualization moveit_setup_assistant moveit_simple_controller_manager robot_state_publisher xacro 

catkin_create_pkg robotic_arm_moveit_interface geometry_msgs message_generation moveit_commander moveit_ros_planning_interface moveit_visual_tools roscpp rospy std_msgs tf  

catkin_create_pkg master robotic_arm_moveit robotic_arm_moveit_interface

cd ~/Workspaces/intrarobots_ws/src/robots/panda
catkin_create_pkg panda_description
catkin_create_pkg panda_gazebo
catkin_create_pkg panda_moveit_config

cd ~/Workspaces/intrarobots_ws/src/robots/wx200
catkin_create_pkg wx200_description
catkin_create_pkg wx200_gazebo
catkin_create_pkg wx200_moveit_config

cd ~/Workspaces/intrarobots_ws
catkin_make