// Generated by gencpp from file custom_messages/GoToPoseConfirmation.msg
// DO NOT EDIT!


#ifndef CUSTOM_MESSAGES_MESSAGE_GOTOPOSECONFIRMATION_H
#define CUSTOM_MESSAGES_MESSAGE_GOTOPOSECONFIRMATION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace custom_messages
{
template <class ContainerAllocator>
struct GoToPoseConfirmation_
{
  typedef GoToPoseConfirmation_<ContainerAllocator> Type;

  GoToPoseConfirmation_()
    : header()
    , robot_name()
    , command_seq(0)
    , success(false)  {
    }
  GoToPoseConfirmation_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , robot_name(_alloc)
    , command_seq(0)
    , success(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _robot_name_type;
  _robot_name_type robot_name;

   typedef uint32_t _command_seq_type;
  _command_seq_type command_seq;

   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::custom_messages::GoToPoseConfirmation_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_messages::GoToPoseConfirmation_<ContainerAllocator> const> ConstPtr;

}; // struct GoToPoseConfirmation_

typedef ::custom_messages::GoToPoseConfirmation_<std::allocator<void> > GoToPoseConfirmation;

typedef boost::shared_ptr< ::custom_messages::GoToPoseConfirmation > GoToPoseConfirmationPtr;
typedef boost::shared_ptr< ::custom_messages::GoToPoseConfirmation const> GoToPoseConfirmationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_messages::GoToPoseConfirmation_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_messages::GoToPoseConfirmation_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_messages::GoToPoseConfirmation_<ContainerAllocator1> & lhs, const ::custom_messages::GoToPoseConfirmation_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.robot_name == rhs.robot_name &&
    lhs.command_seq == rhs.command_seq &&
    lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_messages::GoToPoseConfirmation_<ContainerAllocator1> & lhs, const ::custom_messages::GoToPoseConfirmation_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_messages

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_messages::GoToPoseConfirmation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_messages::GoToPoseConfirmation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_messages::GoToPoseConfirmation_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_messages::GoToPoseConfirmation_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_messages::GoToPoseConfirmation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_messages::GoToPoseConfirmation_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_messages::GoToPoseConfirmation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bf37a5a5bd1d5d54d0cd95b0a2f2076c";
  }

  static const char* value(const ::custom_messages::GoToPoseConfirmation_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbf37a5a5bd1d5d54ULL;
  static const uint64_t static_value2 = 0xd0cd95b0a2f2076cULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_messages::GoToPoseConfirmation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_messages/GoToPoseConfirmation";
  }

  static const char* value(const ::custom_messages::GoToPoseConfirmation_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_messages::GoToPoseConfirmation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"string robot_name\n"
"uint32 command_seq\n"
"bool success\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::custom_messages::GoToPoseConfirmation_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_messages::GoToPoseConfirmation_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.robot_name);
      stream.next(m.command_seq);
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GoToPoseConfirmation_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_messages::GoToPoseConfirmation_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_messages::GoToPoseConfirmation_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "robot_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.robot_name);
    s << indent << "command_seq: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.command_seq);
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MESSAGES_MESSAGE_GOTOPOSECONFIRMATION_H
