// Generated by gencpp from file custom_messages/MoveGripperCommand.msg
// DO NOT EDIT!


#ifndef CUSTOM_MESSAGES_MESSAGE_MOVEGRIPPERCOMMAND_H
#define CUSTOM_MESSAGES_MESSAGE_MOVEGRIPPERCOMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace custom_messages
{
template <class ContainerAllocator>
struct MoveGripperCommand_
{
  typedef MoveGripperCommand_<ContainerAllocator> Type;

  MoveGripperCommand_()
    : header()
    , robot_name()
    , cmd()  {
    }
  MoveGripperCommand_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , robot_name(_alloc)
    , cmd(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _robot_name_type;
  _robot_name_type robot_name;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _cmd_type;
  _cmd_type cmd;





  typedef boost::shared_ptr< ::custom_messages::MoveGripperCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_messages::MoveGripperCommand_<ContainerAllocator> const> ConstPtr;

}; // struct MoveGripperCommand_

typedef ::custom_messages::MoveGripperCommand_<std::allocator<void> > MoveGripperCommand;

typedef boost::shared_ptr< ::custom_messages::MoveGripperCommand > MoveGripperCommandPtr;
typedef boost::shared_ptr< ::custom_messages::MoveGripperCommand const> MoveGripperCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_messages::MoveGripperCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_messages::MoveGripperCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_messages::MoveGripperCommand_<ContainerAllocator1> & lhs, const ::custom_messages::MoveGripperCommand_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.robot_name == rhs.robot_name &&
    lhs.cmd == rhs.cmd;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_messages::MoveGripperCommand_<ContainerAllocator1> & lhs, const ::custom_messages::MoveGripperCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_messages

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_messages::MoveGripperCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_messages::MoveGripperCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_messages::MoveGripperCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_messages::MoveGripperCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_messages::MoveGripperCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_messages::MoveGripperCommand_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_messages::MoveGripperCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c7eca5acbbe328698e1bba54b90270b6";
  }

  static const char* value(const ::custom_messages::MoveGripperCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc7eca5acbbe32869ULL;
  static const uint64_t static_value2 = 0x8e1bba54b90270b6ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_messages::MoveGripperCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_messages/MoveGripperCommand";
  }

  static const char* value(const ::custom_messages::MoveGripperCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_messages::MoveGripperCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"string robot_name\n"
"string cmd\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::custom_messages::MoveGripperCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_messages::MoveGripperCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.robot_name);
      stream.next(m.cmd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveGripperCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_messages::MoveGripperCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_messages::MoveGripperCommand_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "robot_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.robot_name);
    s << indent << "cmd: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.cmd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MESSAGES_MESSAGE_MOVEGRIPPERCOMMAND_H
