// Generated by gencpp from file custom_messages/MoveGripperConfirmation.msg
// DO NOT EDIT!


#ifndef CUSTOM_MESSAGES_MESSAGE_MOVEGRIPPERCONFIRMATION_H
#define CUSTOM_MESSAGES_MESSAGE_MOVEGRIPPERCONFIRMATION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace custom_messages
{
template <class ContainerAllocator>
struct MoveGripperConfirmation_
{
  typedef MoveGripperConfirmation_<ContainerAllocator> Type;

  MoveGripperConfirmation_()
    : header()
    , robot_name()
    , command_id()
    , success(false)  {
    }
  MoveGripperConfirmation_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , robot_name(_alloc)
    , command_id(_alloc)
    , success(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _robot_name_type;
  _robot_name_type robot_name;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _command_id_type;
  _command_id_type command_id;

   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::custom_messages::MoveGripperConfirmation_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_messages::MoveGripperConfirmation_<ContainerAllocator> const> ConstPtr;

}; // struct MoveGripperConfirmation_

typedef ::custom_messages::MoveGripperConfirmation_<std::allocator<void> > MoveGripperConfirmation;

typedef boost::shared_ptr< ::custom_messages::MoveGripperConfirmation > MoveGripperConfirmationPtr;
typedef boost::shared_ptr< ::custom_messages::MoveGripperConfirmation const> MoveGripperConfirmationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_messages::MoveGripperConfirmation_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_messages::MoveGripperConfirmation_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_messages::MoveGripperConfirmation_<ContainerAllocator1> & lhs, const ::custom_messages::MoveGripperConfirmation_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.robot_name == rhs.robot_name &&
    lhs.command_id == rhs.command_id &&
    lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_messages::MoveGripperConfirmation_<ContainerAllocator1> & lhs, const ::custom_messages::MoveGripperConfirmation_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_messages

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_messages::MoveGripperConfirmation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_messages::MoveGripperConfirmation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_messages::MoveGripperConfirmation_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_messages::MoveGripperConfirmation_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_messages::MoveGripperConfirmation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_messages::MoveGripperConfirmation_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_messages::MoveGripperConfirmation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d1e861f7b9dd4217596bf13b98116564";
  }

  static const char* value(const ::custom_messages::MoveGripperConfirmation_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd1e861f7b9dd4217ULL;
  static const uint64_t static_value2 = 0x596bf13b98116564ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_messages::MoveGripperConfirmation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_messages/MoveGripperConfirmation";
  }

  static const char* value(const ::custom_messages::MoveGripperConfirmation_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_messages::MoveGripperConfirmation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"string robot_name\n"
"string command_id\n"
"bool success\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::custom_messages::MoveGripperConfirmation_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_messages::MoveGripperConfirmation_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.robot_name);
      stream.next(m.command_id);
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveGripperConfirmation_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_messages::MoveGripperConfirmation_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_messages::MoveGripperConfirmation_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "robot_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.robot_name);
    s << indent << "command_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.command_id);
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MESSAGES_MESSAGE_MOVEGRIPPERCONFIRMATION_H
