// Generated by gencpp from file robotic_arm_moveit_interface/go_to_pose_confirmation.msg
// DO NOT EDIT!


#ifndef ROBOTIC_ARM_MOVEIT_INTERFACE_MESSAGE_GO_TO_POSE_CONFIRMATION_H
#define ROBOTIC_ARM_MOVEIT_INTERFACE_MESSAGE_GO_TO_POSE_CONFIRMATION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Pose.h>

namespace robotic_arm_moveit_interface
{
template <class ContainerAllocator>
struct go_to_pose_confirmation_
{
  typedef go_to_pose_confirmation_<ContainerAllocator> Type;

  go_to_pose_confirmation_()
    : header()
    , robot_name()
    , target_pose()
    , success(false)  {
    }
  go_to_pose_confirmation_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , robot_name(_alloc)
    , target_pose(_alloc)
    , success(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _robot_name_type;
  _robot_name_type robot_name;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target_pose_type;
  _target_pose_type target_pose;

   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::robotic_arm_moveit_interface::go_to_pose_confirmation_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotic_arm_moveit_interface::go_to_pose_confirmation_<ContainerAllocator> const> ConstPtr;

}; // struct go_to_pose_confirmation_

typedef ::robotic_arm_moveit_interface::go_to_pose_confirmation_<std::allocator<void> > go_to_pose_confirmation;

typedef boost::shared_ptr< ::robotic_arm_moveit_interface::go_to_pose_confirmation > go_to_pose_confirmationPtr;
typedef boost::shared_ptr< ::robotic_arm_moveit_interface::go_to_pose_confirmation const> go_to_pose_confirmationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotic_arm_moveit_interface::go_to_pose_confirmation_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotic_arm_moveit_interface::go_to_pose_confirmation_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robotic_arm_moveit_interface::go_to_pose_confirmation_<ContainerAllocator1> & lhs, const ::robotic_arm_moveit_interface::go_to_pose_confirmation_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.robot_name == rhs.robot_name &&
    lhs.target_pose == rhs.target_pose &&
    lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robotic_arm_moveit_interface::go_to_pose_confirmation_<ContainerAllocator1> & lhs, const ::robotic_arm_moveit_interface::go_to_pose_confirmation_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robotic_arm_moveit_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robotic_arm_moveit_interface::go_to_pose_confirmation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotic_arm_moveit_interface::go_to_pose_confirmation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotic_arm_moveit_interface::go_to_pose_confirmation_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotic_arm_moveit_interface::go_to_pose_confirmation_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotic_arm_moveit_interface::go_to_pose_confirmation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotic_arm_moveit_interface::go_to_pose_confirmation_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotic_arm_moveit_interface::go_to_pose_confirmation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d8653ffd7c3f3bfa775e8baaf947f5e1";
  }

  static const char* value(const ::robotic_arm_moveit_interface::go_to_pose_confirmation_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd8653ffd7c3f3bfaULL;
  static const uint64_t static_value2 = 0x775e8baaf947f5e1ULL;
};

template<class ContainerAllocator>
struct DataType< ::robotic_arm_moveit_interface::go_to_pose_confirmation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotic_arm_moveit_interface/go_to_pose_confirmation";
  }

  static const char* value(const ::robotic_arm_moveit_interface::go_to_pose_confirmation_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotic_arm_moveit_interface::go_to_pose_confirmation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"string robot_name\n"
"geometry_msgs/Pose target_pose\n"
"bool success\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::robotic_arm_moveit_interface::go_to_pose_confirmation_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotic_arm_moveit_interface::go_to_pose_confirmation_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.robot_name);
      stream.next(m.target_pose);
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct go_to_pose_confirmation_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotic_arm_moveit_interface::go_to_pose_confirmation_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotic_arm_moveit_interface::go_to_pose_confirmation_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "robot_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.robot_name);
    s << indent << "target_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target_pose);
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTIC_ARM_MOVEIT_INTERFACE_MESSAGE_GO_TO_POSE_CONFIRMATION_H
